<?xml version="1.0" standalone="no"?>
<!DOCTYPE ChannelDefinitions [
<!ELEMENT ChannelDefinitions (ChannelDefinition)+>
<!ELEMENT ChannelDefinition (DisplayDefinition)*>
<!ATTLIST ChannelDefinition
schema CDATA #REQUIRED
id CDATA #REQUIRED
description CDATA #REQUIRED
component CDATA #REQUIRED
unit CDATA #IMPLIED
unitType CDATA #IMPLIED
sign CDATA #REQUIRED
scale CDATA #REQUIRED
offset CDATA #REQUIRED
byteSize CDATA #REQUIRED
minmax CDATA #REQUIRED
>
<!ELEMENT DisplayDefinition EMPTY>
<!ATTLIST DisplayDefinition
channelValue CDATA #IMPLIED
altValue CDATA #IMPLIED
displayString CDATA #IMPLIED
>
]>
<!--
$Revision: $
Version: 11.0.4
-->
<ChannelDefinitions>
    <ChannelDefinition schema="VIMS" id="77" description="CIDS Strg1 ECM(77)" component="400" unitType="unitless" scale="1.0" offset="0" byteSize="5" sign="0" minmax="0">
    </ChannelDefinition>
    <ChannelDefinition schema="VIMS" id="78" description="CIDS Strg2 ECM(78)" component="400" unitType="unitless" scale="1.0" offset="0" byteSize="5" sign="0" minmax="0">
    </ChannelDefinition>
    <ChannelDefinition schema="VIMS" id="79" description="CIDs Payld ECM(79)" component="700" unitType="unitless" scale="1.0" offset="0" byteSize="5" sign="0" minmax="0">
    </ChannelDefinition>
    <ChannelDefinition schema="VIMS" id="80" description="CIDs Advsr ECM(80)" component="700" unitType="unitless" scale="1.0" offset="0" byteSize="5" sign="0" minmax="0">
    </ChannelDefinition>
    <ChannelDefinition schema="VIMS" id="81" description="Dimmer Sw(81)" component="14" unitType="unitless" scale="1.0" offset="0" byteSize="5" sign="0" minmax="0">
    </ChannelDefinition>
    <ChannelDefinition schema="VIMS" id="82" description="CIDs Abl I/m(82)" component="12" unitType="unitless" scale="1.0" offset="0" byteSize="5" sign="0" minmax="0">
    </ChannelDefinition>
    <ChannelDefinition schema="VIMS" id="83" description="CIDs F Eng(83)" component="7" unitType="unitless" scale="1.0" offset="0" byteSize="5" sign="0" minmax="0">
    </ChannelDefinition>
    <ChannelDefinition schema="VIMS" id="84" description="CIDs R Eng(84)" component="8" unitType="unitless" scale="1.0" offset="0" byteSize="5" sign="0" minmax="0">
    </ChannelDefinition>
    <ChannelDefinition schema="VIMS" id="85" description="CIDs Chassis(85)" component="9" unitType="unitless" scale="1.0" offset="0" byteSize="5" sign="0" minmax="0">
    </ChannelDefinition>
    <ChannelDefinition schema="VIMS" id="86" description="CIDs Shadow Box(86)" component="10" unitType="unitless" scale="1.0" offset="0" byteSize="5" sign="0" minmax="0">
    </ChannelDefinition>
    <ChannelDefinition schema="VIMS" id="87" description="CIDs SEMS(87)" component="1" unitType="unitless" scale="1.0" offset="0" byteSize="5" sign="0" minmax="0">
    </ChannelDefinition>
    <ChannelDefinition schema="VIMS" id="88" description="CIDs ECM(88)" component="1" unitType="unitless" scale="1.0" offset="0" byteSize="5" sign="0" minmax="0">
    </ChannelDefinition>
    <ChannelDefinition schema="VIMS" id="89" description="CIDs I/M 1(89)" component="4" unitType="unitless" scale="1.0" offset="0" byteSize="5" sign="0" minmax="0">
    </ChannelDefinition>
    <ChannelDefinition schema="VIMS" id="90" description="CIDs I/M 2(90)" component="5" unitType="unitless" scale="1.0" offset="0" byteSize="5" sign="0" minmax="0">
    </ChannelDefinition>
    <ChannelDefinition schema="VIMS" id="91" description="CIDs Exh Ctrl(91)" component="12" unitType="unitless" scale="1.0" offset="0" byteSize="5" sign="0" minmax="0">
    </ChannelDefinition>
    <ChannelDefinition schema="VIMS" id="92" description="CIDs Trn Ctrl(92)" component="2" unitType="unitless" scale="1.0" offset="0" byteSize="5" sign="0" minmax="0">
    </ChannelDefinition>
    <ChannelDefinition schema="VIMS" id="93" description="Main Modul VIMS(93)" component="14" unitType="unitless" scale="1.0" offset="0" byteSize="5" sign="0" minmax="0">
    </ChannelDefinition>
    <ChannelDefinition schema="VIMS" id="94" description="CIDs ARC(94)" component="3" unitType="unitless" scale="1.0" offset="0" byteSize="5" sign="0" minmax="0">
    </ChannelDefinition>
    <ChannelDefinition schema="VIMS" id="95" description="CIDs M/C Modul(95)" component="19" unitType="unitless" scale="1.0" offset="0" byteSize="5" sign="0" minmax="0">
    </ChannelDefinition>
    <ChannelDefinition schema="VIMS" id="96" description="CIDs Impl Ctrl(96)" component="500" unitType="unitless" scale="1.0" offset="0" byteSize="5" sign="0" minmax="0">
    </ChannelDefinition>
    <ChannelDefinition schema="VIMS" id="97" description="CIDs I/M 3(97)" component="6" unitType="unitless" scale="1.0" offset="0" byteSize="5" sign="0" minmax="0">
    </ChannelDefinition>
    <ChannelDefinition schema="VIMS" id="98" description="CIDs IBC(98)" component="4" unitType="unitless" scale="1.0" offset="0" byteSize="5" sign="0" minmax="0">
    </ChannelDefinition>
    <ChannelDefinition schema="VIMS" id="99" description="Thrttl Lck Enbl(99)" component="100" unitType="unitless" scale="1.0" offset="0" byteSize="1" sign="0" minmax="0">
        <DisplayDefinition channelValue="0.0" altValue="10.0" displayString="Off"/>
        <DisplayDefinition channelValue="1.0" altValue="20.0" displayString="On"/>
        <DisplayDefinition channelValue="2.0" altValue="30.0" displayString="Lost Cycle"/>
        <DisplayDefinition channelValue="224.0" altValue="1.0" displayString="Calc Ready"/>
        <DisplayDefinition channelValue="225.0" altValue="2.0" displayString="Calc Not Ready"/>
        <DisplayDefinition channelValue="226.0" altValue="3.0" displayString="Lost Cycle"/>
    </ChannelDefinition>
    <ChannelDefinition schema="VIMS" id="100" description="Eng Spd(100)" component="100" unit="revolutions per minute" unitType="angular velocity" scale="0.5" offset="0" byteSize="5" sign="0" minmax="0">
    </ChannelDefinition>
    <ChannelDefinition schema="VIMS" id="101" description="Trbo In Pres(101)" component="100" unit="kilopascal" unitType="pressure" scale="0.5" offset="0" byteSize="5" sign="0" minmax="0">
    </ChannelDefinition>
    <ChannelDefinition schema="VIMS" id="102" description="Lt Trbo In Pres(102)" component="100" unit="kilopascal" unitType="pressure" scale="0.5" offset="0" byteSize="5" sign="0" minmax="0">
    </ChannelDefinition>
    <ChannelDefinition schema="VIMS" id="103" description="Rt Trbo In Pres(103)" component="100" unit="kilopascal" unitType="pressure" scale="0.5" offset="0" byteSize="5" sign="0" minmax="0">
    </ChannelDefinition>
    <ChannelDefinition schema="VIMS" id="104" description="Air Fltr(104)" component="100" unit="kilopascal" unitType="pressure" scale="0.5" offset="0" byteSize="5" sign="0" minmax="0">
    </ChannelDefinition>
    <ChannelDefinition schema="VIMS" id="105" description="Boost Pres(105)" component="100" unit="kilopascal" unitType="pressure" scale="0.5" offset="0" byteSize="5" sign="0" minmax="0">
    </ChannelDefinition>
    <ChannelDefinition schema="VIMS" id="106" description="Lt Exh Temp(106)" component="100" unit="celsius" unitType="temperature" scale="1.0" offset="0" byteSize="5" sign="0" minmax="0">
    </ChannelDefinition>
    <ChannelDefinition schema="VIMS" id="107" description="Rt-Lt Exh Temp(107)" component="100" unit="differential celsius" unitType="differential temperature" scale="1.0" offset="0" byteSize="5" sign="0" minmax="0">
    </ChannelDefinition>
    <ChannelDefinition schema="VIMS" id="108" description="Rt Exh Temp(108)" component="100" unit="celsius" unitType="temperature" scale="1.0" offset="0" byteSize="5" sign="0" minmax="0">
    </ChannelDefinition>
    <ChannelDefinition schema="VIMS" id="109" description="Trbo Out Pres(109)" component="100" unit="kilopascal" unitType="pressure" scale="0.5" offset="0" byteSize="5" sign="0" minmax="0">
    </ChannelDefinition>
    <ChannelDefinition schema="VIMS" id="110" description="Aftrclr Temp(110)" component="100" unit="celsius" unitType="temperature" scale="1.0" offset="0" byteSize="5" sign="0" minmax="0">
    </ChannelDefinition>
    <ChannelDefinition schema="VIMS" id="111" description="F Aftrclr Temp(111)" component="100" unit="celsius" unitType="temperature" scale="1.0" offset="0" byteSize="5" sign="0" minmax="0">
    </ChannelDefinition>
    <ChannelDefinition schema="VIMS" id="112" description="R Aftrclr Temp(112)" component="100" unit="celsius" unitType="temperature" scale="1.0" offset="0" byteSize="5" sign="0" minmax="0">
    </ChannelDefinition>
    <ChannelDefinition schema="VIMS" id="113" description="Start Aid Sw(113)" component="100" unitType="unitless" scale="1.0" offset="0" byteSize="1" sign="0" minmax="0">
        <DisplayDefinition channelValue="0.0" altValue="10.0" displayString="Off"/>
        <DisplayDefinition channelValue="1.0" altValue="20.0" displayString="On"/>
        <DisplayDefinition channelValue="2.0" altValue="30.0" displayString="Lost Cycle"/>
        <DisplayDefinition channelValue="224.0" altValue="1.0" displayString="Calc Ready"/>
        <DisplayDefinition channelValue="225.0" altValue="2.0" displayString="Calc Not Ready"/>
        <DisplayDefinition channelValue="226.0" altValue="3.0" displayString="Lost Cycle"/>
    </ChannelDefinition>
    <ChannelDefinition schema="VIMS" id="114" description="Wastegate Pos(114)" component="100" unit="percent" unitType="ratio" scale="0.5" offset="0" byteSize="6" sign="0" minmax="0">
    </ChannelDefinition>
    <ChannelDefinition schema="VIMS" id="115" description="Cool Fan Spd(115)" component="100" unit="revolutions per minute" unitType="angular velocity" scale="0.5" offset="0" byteSize="4" sign="0" minmax="0">
    </ChannelDefinition>
    <ChannelDefinition schema="VIMS" id="116" description="Eng Cold Mode(116)" component="100" unitType="unitless" scale="1.0" offset="0" byteSize="3" sign="0" minmax="0">
        <DisplayDefinition channelValue="0.0" altValue="10.0" displayString="Off"/>
        <DisplayDefinition channelValue="1.0" altValue="20.0" displayString="On"/>
        <DisplayDefinition channelValue="127.0" altValue="20.0" displayString="On"/>
        <DisplayDefinition channelValue="128.0" altValue="20.0" displayString="On"/>
        <DisplayDefinition channelValue="240.0" altValue="20.0" displayString="On"/>
    </ChannelDefinition>
    <ChannelDefinition schema="VIMS" id="117" description="Eng Derate(117)" component="100" unit="percent" unitType="ratio" scale="0.5" offset="0" byteSize="1" sign="0" minmax="0">
    </ChannelDefinition>
    <ChannelDefinition schema="VIMS" id="118" description="Air Fltr(118)" component="100" unit="kilopascal" unitType="pressure" scale="0.5" offset="0" byteSize="5" sign="0" minmax="0">
    </ChannelDefinition>
    <ChannelDefinition schema="VIMS" id="119" description="Ether Injec(119)" component="100" unitType="unitless" scale="1.0" offset="0" byteSize="2" sign="0" minmax="0">
        <DisplayDefinition channelValue="0.0" altValue="10.0" displayString="Off"/>
        <DisplayDefinition channelValue="1.0" altValue="20.0" displayString="On"/>
        <DisplayDefinition channelValue="2.0" altValue="30.0" displayString="Lost Cycle"/>
        <DisplayDefinition channelValue="224.0" altValue="1.0" displayString="Calc Ready"/>
        <DisplayDefinition channelValue="225.0" altValue="2.0" displayString="Calc Not Ready"/>
        <DisplayDefinition channelValue="226.0" altValue="3.0" displayString="Lost Cycle"/>
    </ChannelDefinition>
    <ChannelDefinition schema="VIMS" id="120" description="Fuel Pos(120)" component="100" unitType="unitless" scale="0.0050" offset="0" byteSize="4" sign="0" minmax="0">
    </ChannelDefinition>
    <ChannelDefinition schema="VIMS" id="121" description="Eng Load(121)" component="100" unit="percent" unitType="ratio" scale="1.0" offset="0" byteSize="3" sign="0" minmax="0">
    </ChannelDefinition>
    <ChannelDefinition schema="VIMS" id="122" description="Fuel Fltr(122)" component="100" unitType="unitless" scale="1.0" offset="0" byteSize="2" sign="0" minmax="0">
        <DisplayDefinition channelValue="0.0" altValue="20.0" displayString="OK"/>
        <DisplayDefinition channelValue="1.0" altValue="10.0" displayString="Plugged"/>
        <DisplayDefinition channelValue="10.0" altValue="20.0" displayString="OK"/>
        <DisplayDefinition channelValue="96.0" altValue="10.0" displayString="Plugged"/>
        <DisplayDefinition channelValue="102.0" altValue="10.0" displayString="Plugged"/>
        <DisplayDefinition channelValue="127.0" altValue="10.0" displayString="Plugged"/>
    </ChannelDefinition>
    <ChannelDefinition schema="VIMS" id="123" description="Fuel Lvl(123)" component="100" unit="percent" unitType="ratio" scale="0.0050" offset="0" byteSize="5" sign="0" minmax="0">
    </ChannelDefinition>
    <ChannelDefinition schema="VIMS" id="124" description="Throttl Sw Pos(124)" component="100" unitType="unitless" scale="1.0" offset="0" byteSize="1" sign="0" minmax="0">
    </ChannelDefinition>
    <ChannelDefinition schema="VIMS" id="125" description="Throttl Pos(125)" component="100" unit="percent" unitType="ratio" scale="0.4" offset="0" byteSize="3" sign="0" minmax="0">
    </ChannelDefinition>
    <ChannelDefinition schema="VIMS" id="126" description="Fuel Flow(126)" component="100" unit="litres per hour" unitType="flow" scale="0.05" offset="0" byteSize="4" sign="0" minmax="0">
    </ChannelDefinition>
    <ChannelDefinition schema="VIMS" id="127" description="Fuel Flow Engl(127)" component="100" unit="gallons per hour" unitType="flow" scale="0.0156" offset="0" byteSize="4" sign="0" minmax="0">
    </ChannelDefinition>
    <ChannelDefinition schema="VIMS" id="128" description="Fuel Pres(128)" component="100" unit="kilopascal" unitType="pressure" scale="0.5" offset="0" byteSize="4" sign="0" minmax="0">
    </ChannelDefinition>
    <ChannelDefinition schema="VIMS" id="129" description="Eng Fuel Rate(129)" component="100" unit="litres per hour" unitType="flow" scale="0.05" offset="0" byteSize="4" sign="0" minmax="0">
    </ChannelDefinition>
    <ChannelDefinition schema="VIMS" id="130" description="Eng Oil Lvl(130)" component="100" unitType="unitless" scale="1.0" offset="0" byteSize="1" sign="0" minmax="0">
        <DisplayDefinition channelValue="0.0" altValue="20.0" displayString="OK"/>
        <DisplayDefinition channelValue="1.0" altValue="10.0" displayString="Low"/>
        <DisplayDefinition channelValue="127.0" altValue="10.0" displayString="Low"/>
    </ChannelDefinition>
    <ChannelDefinition schema="VIMS" id="131" description="Eng Oil Pres(131)" component="100" unit="kilopascal" unitType="pressure" scale="0.5" offset="0" byteSize="5" sign="0" minmax="0">
    </ChannelDefinition>
    <ChannelDefinition schema="VIMS" id="132" description="Eng Oil Pres Ab(132)" component="100" unit="kilopascal" unitType="pressure" scale="0.5" offset="0" byteSize="5" sign="0" minmax="0">
    </ChannelDefinition>
    <ChannelDefinition schema="VIMS" id="133" description="Cnkcase Pres(133)" component="100" unit="kilopascal" unitType="pressure" scale="0.1" offset="0" byteSize="5" sign="0" minmax="0">
    </ChannelDefinition>
    <ChannelDefinition schema="VIMS" id="134" description="Eng Cool Flow(134)" component="100" unitType="unitless" scale="1.0" offset="0" byteSize="2" sign="0" minmax="0">
        <DisplayDefinition channelValue="0.0" altValue="10.0" displayString="Low"/>
        <DisplayDefinition channelValue="1.0" altValue="20.0" displayString="OK"/>
        <DisplayDefinition channelValue="127.0" altValue="20.0" displayString="OK"/>
    </ChannelDefinition>
    <ChannelDefinition schema="VIMS" id="135" description="Eng Cool Temp(135)" component="100" unit="celsius" unitType="temperature" scale="1.0" offset="0" byteSize="5" sign="0" minmax="0">
    </ChannelDefinition>
    <ChannelDefinition schema="VIMS" id="136" description="Hyd Coolr Blkr(136)" component="100" unitType="unitless" scale="1.0" offset="0" byteSize="2" sign="0" minmax="0">
        <DisplayDefinition channelValue="0.0" altValue="10.0" displayString="Off"/>
        <DisplayDefinition channelValue="1.0" altValue="20.0" displayString="On"/>
        <DisplayDefinition channelValue="2.0" altValue="30.0" displayString="Lost Cycle"/>
        <DisplayDefinition channelValue="224.0" altValue="1.0" displayString="Calc Ready"/>
        <DisplayDefinition channelValue="225.0" altValue="2.0" displayString="Calc Not Ready"/>
        <DisplayDefinition channelValue="226.0" altValue="3.0" displayString="Lost Cycle"/>
    </ChannelDefinition>
    <ChannelDefinition schema="VIMS" id="137" description="Aftrclr Lvl(137)" component="100" unitType="unitless" scale="1.0" offset="0" byteSize="1" sign="0" minmax="0">
        <DisplayDefinition channelValue="0.0" altValue="20.0" displayString="OK"/>
        <DisplayDefinition channelValue="1.0" altValue="10.0" displayString="Low"/>
        <DisplayDefinition channelValue="127.0" altValue="10.0" displayString="Low"/>
    </ChannelDefinition>
    <ChannelDefinition schema="VIMS" id="138" description="Eng Cool Lvl(138)" component="100" unitType="unitless" scale="1.0" offset="0" byteSize="1" sign="0" minmax="0">
        <DisplayDefinition channelValue="0.0" altValue="20.0" displayString="OK"/>
        <DisplayDefinition channelValue="1.0" altValue="10.0" displayString="Low"/>
        <DisplayDefinition channelValue="127.0" altValue="10.0" displayString="Low"/>
    </ChannelDefinition>
    <ChannelDefinition schema="VIMS" id="139" description="Eng Oil Renewal(139)" component="100" unitType="unitless" scale="1.0" offset="0" byteSize="2" sign="0" minmax="0">
        <DisplayDefinition channelValue="0.0" altValue="10.0" displayString="Off"/>
        <DisplayDefinition channelValue="1.0" altValue="20.0" displayString="On"/>
        <DisplayDefinition channelValue="2.0" altValue="30.0" displayString="Aborted"/>
    </ChannelDefinition>
    <ChannelDefinition schema="VIMS" id="140" description="Sys Voltage(140)" component="100" unit="volt" unitType="potential difference" scale="0.0010" offset="0" byteSize="4" sign="0" minmax="0">
    </ChannelDefinition>
    <ChannelDefinition schema="VIMS" id="141" description="Main Pilot Pres(141)" component="500" unit="kilopascal" unitType="pressure" scale="1.0" offset="0" byteSize="4" sign="0" minmax="0">
    </ChannelDefinition>
    <ChannelDefinition schema="VIMS" id="142" description="Impl Pres(142)" component="500" unit="kilopascal" unitType="pressure" scale="1.0" offset="0" byteSize="4" sign="0" minmax="0">
    </ChannelDefinition>
    <ChannelDefinition schema="VIMS" id="143" description="Impl Pres Sw(143)" component="500" unitType="unitless" scale="1.0" offset="0" byteSize="2" sign="0" minmax="0">
        <DisplayDefinition channelValue="0.0" altValue="10.0" displayString="Low"/>
        <DisplayDefinition channelValue="1.0" altValue="20.0" displayString="High"/>
        <DisplayDefinition channelValue="127.0" altValue="20.0" displayString="High"/>
    </ChannelDefinition>
    <ChannelDefinition schema="VIMS" id="144" description="Unfltr Oil Pres(144)" component="100" unit="kilopascal" unitType="pressure" scale="0.5" offset="0" byteSize="4" sign="0" minmax="0">
    </ChannelDefinition>
    <ChannelDefinition schema="VIMS" id="145" description="Hi Boost Pres(145)" component="100" unitType="unitless" scale="1.0" offset="0" byteSize="1" sign="0" minmax="0">
        <DisplayDefinition channelValue="0.0" altValue="10.0" displayString="Inactive"/>
        <DisplayDefinition channelValue="1.0" altValue="20.0" displayString="Active"/>
        <DisplayDefinition channelValue="2.0" altValue="20.0" displayString="Active"/>
        <DisplayDefinition channelValue="3.0" altValue="20.0" displayString="Active"/>
        <DisplayDefinition channelValue="4.0" altValue="20.0" displayString="Active"/>
        <DisplayDefinition channelValue="5.0" altValue="20.0" displayString="Active"/>
        <DisplayDefinition channelValue="6.0" altValue="20.0" displayString="Active"/>
        <DisplayDefinition channelValue="127.0" altValue="30.0" displayString="Active"/>
    </ChannelDefinition>
    <ChannelDefinition schema="VIMS" id="146" description="Lo Boost Pres(146)" component="100" unitType="unitless" scale="1.0" offset="0" byteSize="1" sign="0" minmax="0">
        <DisplayDefinition channelValue="0.0" altValue="20.0" displayString="OK"/>
        <DisplayDefinition channelValue="1.0" altValue="10.0" displayString="Low"/>
        <DisplayDefinition channelValue="127.0" altValue="10.0" displayString="Low"/>
    </ChannelDefinition>
    <ChannelDefinition schema="VIMS" id="147" description="Cnkcase Pres(147)" component="100" unit="kilopascal" unitType="pressure" scale="0.1" offset="0" byteSize="5" sign="0" minmax="0">
    </ChannelDefinition>
    <ChannelDefinition schema="VIMS" id="148" description="Eng Timing(148)" component="100" unit="degrees" unitType="plane angle" scale="0.01" offset="0" byteSize="4" sign="0" minmax="0">
    </ChannelDefinition>
    <ChannelDefinition schema="VIMS" id="149" description="Cold Cyl Cutout(149)" component="100" unitType="unitless" scale="1.0" offset="0" byteSize="3" sign="0" minmax="0">
        <DisplayDefinition channelValue="0.0" altValue="10.0" displayString="Disabled"/>
        <DisplayDefinition channelValue="1.0" altValue="20.0" displayString="Enabled"/>
        <DisplayDefinition channelValue="12.0" altValue="20.0" displayString="Enabled"/>
        <DisplayDefinition channelValue="13.0" altValue="10.0" displayString="Disabled"/>
    </ChannelDefinition>
    <ChannelDefinition schema="VIMS" id="150" description="Ave Cyl Temp(150)" component="100" unit="celsius" unitType="temperature" scale="1.0" offset="0" byteSize="5" sign="0" minmax="0">
    </ChannelDefinition>
    <ChannelDefinition schema="VIMS" id="151" description="Inj-Cyl 1 Temp(151)" component="100" unit="celsius" unitType="temperature" scale="1.0" offset="0" byteSize="5" sign="0" minmax="0">
    </ChannelDefinition>
    <ChannelDefinition schema="VIMS" id="152" description="Inj-Cyl 2 Temp(152)" component="100" unit="celsius" unitType="temperature" scale="1.0" offset="0" byteSize="5" sign="0" minmax="0">
    </ChannelDefinition>
    <ChannelDefinition schema="VIMS" id="153" description="Inj-Cyl 3 Temp(153)" component="100" unit="celsius" unitType="temperature" scale="1.0" offset="0" byteSize="5" sign="0" minmax="0">
    </ChannelDefinition>
    <ChannelDefinition schema="VIMS" id="154" description="Inj-Cyl 4 Temp(154)" component="100" unit="celsius" unitType="temperature" scale="1.0" offset="0" byteSize="5" sign="0" minmax="0">
    </ChannelDefinition>
    <ChannelDefinition schema="VIMS" id="155" description="Inj-Cyl 5 Temp(155)" component="100" unit="celsius" unitType="temperature" scale="1.0" offset="0" byteSize="5" sign="0" minmax="0">
    </ChannelDefinition>
    <ChannelDefinition schema="VIMS" id="156" description="Inj-Cyl 6 Temp(156)" component="100" unit="celsius" unitType="temperature" scale="1.0" offset="0" byteSize="5" sign="0" minmax="0">
    </ChannelDefinition>
    <ChannelDefinition schema="VIMS" id="157" description="Inj-Cyl 7 Temp(157)" component="100" unit="celsius" unitType="temperature" scale="1.0" offset="0" byteSize="5" sign="0" minmax="0">
    </ChannelDefinition>
    <ChannelDefinition schema="VIMS" id="158" description="Inj-Cyl 8 Temp(158)" component="100" unit="celsius" unitType="temperature" scale="1.0" offset="0" byteSize="5" sign="0" minmax="0">
    </ChannelDefinition>
    <ChannelDefinition schema="VIMS" id="159" description="Inj-Cyl 9 Temp(159)" component="100" unit="celsius" unitType="temperature" scale="1.0" offset="0" byteSize="5" sign="0" minmax="0">
    </ChannelDefinition>
    <ChannelDefinition schema="VIMS" id="160" description="Inj-Cyl 10 Temp(160)" component="100" unit="celsius" unitType="temperature" scale="1.0" offset="0" byteSize="5" sign="0" minmax="0">
    </ChannelDefinition>
    <ChannelDefinition schema="VIMS" id="161" description="Inj-Cyl 11 Temp(161)" component="100" unit="celsius" unitType="temperature" scale="1.0" offset="0" byteSize="5" sign="0" minmax="0">
    </ChannelDefinition>
    <ChannelDefinition schema="VIMS" id="162" description="Inj-Cyl 12 Temp(162)" component="100" unit="celsius" unitType="temperature" scale="1.0" offset="0" byteSize="5" sign="0" minmax="0">
    </ChannelDefinition>
    <ChannelDefinition schema="VIMS" id="163" description="Inj-Cyl 13 Temp(163)" component="100" unit="celsius" unitType="temperature" scale="1.0" offset="0" byteSize="5" sign="0" minmax="0">
    </ChannelDefinition>
    <ChannelDefinition schema="VIMS" id="164" description="Inj-Cyl 14 Temp(164)" component="100" unit="celsius" unitType="temperature" scale="1.0" offset="0" byteSize="5" sign="0" minmax="0">
    </ChannelDefinition>
    <ChannelDefinition schema="VIMS" id="165" description="Inj-Cyl 15 Temp(165)" component="100" unit="celsius" unitType="temperature" scale="1.0" offset="0" byteSize="5" sign="0" minmax="0">
    </ChannelDefinition>
    <ChannelDefinition schema="VIMS" id="166" description="Inj-Cyl 16 Temp(166)" component="100" unit="celsius" unitType="temperature" scale="1.0" offset="0" byteSize="5" sign="0" minmax="0">
    </ChannelDefinition>
    <ChannelDefinition schema="VIMS" id="167" description="Eng Prelube(167)" component="100" unitType="unitless" scale="1.0" offset="0" byteSize="3" sign="0" minmax="0">
        <DisplayDefinition channelValue="0.0" altValue="10.0" displayString="Off"/>
        <DisplayDefinition channelValue="1.0" altValue="20.0" displayString="On"/>
        <DisplayDefinition channelValue="2.0" altValue="30.0" displayString="Disabled"/>
        <DisplayDefinition channelValue="3.0" altValue="40.0" displayString="Completed"/>
    </ChannelDefinition>
    <ChannelDefinition schema="VIMS" id="168" description="Lt Air Fltr Res(168)" component="100" unit="kilopascal" unitType="pressure" scale="0.1" offset="0" byteSize="4" sign="0" minmax="0">
    </ChannelDefinition>
    <ChannelDefinition schema="VIMS" id="169" description="Rt Air Fltr Res(169)" component="100" unit="kilopascal" unitType="pressure" scale="0.1" offset="0" byteSize="4" sign="0" minmax="0">
    </ChannelDefinition>
    <ChannelDefinition schema="VIMS" id="170" description="Torq Limit(170)" component="100" unit="millimetre" unitType="length" scale="1.0" offset="0" byteSize="6" sign="0" minmax="0">
    </ChannelDefinition>
    <ChannelDefinition schema="VIMS" id="171" description="Eng Oil Pres St(171)" component="100" unitType="unitless" scale="1.0" offset="0" byteSize="1" sign="0" minmax="0">
        <DisplayDefinition channelValue="0.0" altValue="20.0" displayString="OK"/>
        <DisplayDefinition channelValue="1.0" altValue="10.0" displayString="Low"/>
        <DisplayDefinition channelValue="127.0" altValue="10.0" displayString="Low"/>
    </ChannelDefinition>
    <ChannelDefinition schema="VIMS" id="172" description="Crnk WO Inj St(172)" component="100" unitType="unitless" scale="1.0" offset="0" byteSize="1" sign="0" minmax="0">
        <DisplayDefinition channelValue="0.0" altValue="10.0" displayString="Off"/>
        <DisplayDefinition channelValue="1.0" altValue="20.0" displayString="On"/>
        <DisplayDefinition channelValue="2.0" altValue="30.0" displayString="Lost Cycle"/>
        <DisplayDefinition channelValue="224.0" altValue="1.0" displayString="Calc Ready"/>
        <DisplayDefinition channelValue="225.0" altValue="2.0" displayString="Calc Not Ready"/>
        <DisplayDefinition channelValue="226.0" altValue="3.0" displayString="Lost Cycle"/>
    </ChannelDefinition>
    <ChannelDefinition schema="VIMS" id="173" description="Throttl Sw1 St(173)" component="100" unitType="unitless" scale="1.0" offset="0" byteSize="1" sign="0" minmax="0">
        <DisplayDefinition channelValue="0.0" altValue="10.0" displayString="Off"/>
        <DisplayDefinition channelValue="1.0" altValue="20.0" displayString="On"/>
        <DisplayDefinition channelValue="2.0" altValue="30.0" displayString="Lost Cycle"/>
        <DisplayDefinition channelValue="224.0" altValue="1.0" displayString="Calc Ready"/>
        <DisplayDefinition channelValue="225.0" altValue="2.0" displayString="Calc Not Ready"/>
        <DisplayDefinition channelValue="226.0" altValue="3.0" displayString="Lost Cycle"/>
    </ChannelDefinition>
    <ChannelDefinition schema="VIMS" id="174" description="Throttl Sw2 St(174)" component="100" unitType="unitless" scale="1.0" offset="0" byteSize="1" sign="0" minmax="0">
        <DisplayDefinition channelValue="0.0" altValue="10.0" displayString="Off"/>
        <DisplayDefinition channelValue="1.0" altValue="20.0" displayString="On"/>
        <DisplayDefinition channelValue="2.0" altValue="30.0" displayString="Lost Cycle"/>
        <DisplayDefinition channelValue="224.0" altValue="1.0" displayString="Calc Ready"/>
        <DisplayDefinition channelValue="225.0" altValue="2.0" displayString="Calc Not Ready"/>
        <DisplayDefinition channelValue="226.0" altValue="3.0" displayString="Lost Cycle"/>
    </ChannelDefinition>
    <ChannelDefinition schema="VIMS" id="175" description="Throttl Sw3 St(175)" component="100" unitType="unitless" scale="1.0" offset="0" byteSize="1" sign="0" minmax="0">
        <DisplayDefinition channelValue="0.0" altValue="10.0" displayString="Off"/>
        <DisplayDefinition channelValue="1.0" altValue="20.0" displayString="On"/>
        <DisplayDefinition channelValue="2.0" altValue="30.0" displayString="Lost Cycle"/>
        <DisplayDefinition channelValue="224.0" altValue="1.0" displayString="Calc Ready"/>
        <DisplayDefinition channelValue="225.0" altValue="2.0" displayString="Calc Not Ready"/>
        <DisplayDefinition channelValue="226.0" altValue="3.0" displayString="Lost Cycle"/>
    </ChannelDefinition>
    <ChannelDefinition schema="VIMS" id="176" description="Throttl Sw4 St(176)" component="100" unitType="unitless" scale="1.0" offset="0" byteSize="1" sign="0" minmax="0">
        <DisplayDefinition channelValue="0.0" altValue="10.0" displayString="Off"/>