<?xml version="1.0" standalone="no"?>
<!DOCTYPE CumulativeConfigurations [
<!ELEMENT CumulativeConfigurations (CumulativeConfiguration)+>
<!ELEMENT CumulativeConfiguration (Cumulative)+>
<!ATTLIST CumulativeConfiguration
model CDATA #REQUIRED
>
<!ELEMENT Cumulative EMPTY>
<!ATTLIST Cumulative
schema CDATA #REQUIRED
id CDATA #REQUIRED
unit CDATA #IMPLIED
unitType CDATA #IMPLIED
scale CDATA #REQUIRED
>
]>
<CumulativeConfigurations>
    <CumulativeConfiguration model="200CII" >
        <Cumulative schema="VIMS" id="1" unit="count" unitType="unitless" scale="1.0" />
        <Cumulative schema="VIMS" id="2" unit="count" unitType="unitless" scale="1.0" />
        <Cumulative schema="VIMS" id="3" unit="count" unitType="unitless" scale="1.0" />
        <Cumulative schema="VIMS" id="4" unit="count" unitType="unitless" scale="1.0" />
        <Cumulative schema="VIMS" id="5" unit="count" unitType="unitless" scale="1.0" />
        <Cumulative schema="VIMS" id="6" unit="count" unitType="unitless" scale="1.0" />
        <Cumulative schema="VIMS" id="7" unit="count" unitType="unitless" scale="1.0" />
        <Cumulative schema="VIMS" id="8" unit="count" unitType="unitless" scale="1.0" />
        <Cumulative schema="VIMS" id="10" unit="count" unitType="unitless" scale="1.0" />
        <Cumulative schema="VIMS" id="11" unit="count" unitType="unitless" scale="1.0" />
        <Cumulative schema="VIMS" id="12" unit="count" unitType="unitless" scale="1.0" />
        <Cumulative schema="VIMS" id="13" unit="count" unitType="unitless" scale="1.0" />
        <Cumulative schema="VIMS" id="14" unit="count" unitType="unitless" scale="1.0" />
        <Cumulative schema="VIMS" id="15" unit="count" unitType="unitless" scale="1.0" />
        <Cumulative schema="VIMS" id="16" unit="count" unitType="unitless" scale="1.0" />
        <Cumulative schema="VIMS" id="17" unit="count" unitType="unitless" scale="1.0" />
        <Cumulative schema="VIMS" id="18" unit="count" unitType="unitless" scale="1.0" />
        <Cumulative schema="VIMS" id="19" unit="count" unitType="unitless" scale="1.0" />
        <Cumulative schema="VIMS" id="20" unit="count" unitType="unitless" scale="1.0" />
        <Cumulative schema="VIMS" id="21" unit="count" unitType="unitless" scale="1.0" />
        <Cumulative schema="VIMS" id="22" unit="count" unitType="unitless" scale="1.0" />
        <Cumulative schema="VIMS" id="23" unit="count" unitType="unitless" scale="1.0" />
        <Cumulative schema="VIMS" id="24" unit="mile" unitType="odometer" scale="1.0" />
        <Cumulative schema="VIMS" id="25" unit="hour" unitType="duration" scale="6.944000051589683E-5" />
        <Cumulative schema="VIMS" id="26" unit="hour" unitType="duration" scale="6.944000051589683E-5" />
        <Cumulative schema="VIMS" id="27" unit="hour" unitType="duration" scale="6.944000051589683E-5" />
        <Cumulative schema="VIMS" id="28" unit="hour" unitType="duration" scale="6.944000051589683E-5" />
        <Cumulative schema="VIMS" id="29" unit="hour" unitType="duration" scale="6.944000051589683E-5" />
        <Cumulative schema="VIMS" id="30" unit="hour" unitType="duration" scale="6.944000051589683E-5" />
        <Cumulative schema="VIMS" id="31" unit="hour" unitType="duration" scale="6.944000051589683E-5" />
        <Cumulative schema="VIMS" id="32" unit="hour" unitType="duration" scale="6.944000051589683E-5" />
        <Cumulative schema="VIMS" id="33" unit="hour" unitType="duration" scale="6.944000051589683E-5" />
        <Cumulative schema="VIMS" id="42" unit="count" unitType="unitless" scale="1.0" />
        <Cumulative schema="VIMS" id="45" unit="hour" unitType="duration" scale="6.944000051589683E-5" />
        <Cumulative schema="VIMS" id="46" unit="hour" unitType="duration" scale="6.944000051589683E-5" />
        <Cumulative schema="VIMS" id="47" unit="hour" unitType="duration" scale="6.944000051589683E-5" />
        <Cumulative schema="VIMS" id="48" unit="hour" unitType="duration" scale="6.944000051589683E-5" />
        <Cumulative schema="VIMS" id="49" unit="hour" unitType="duration" scale="6.944000051589683E-5" />
        <Cumulative schema="VIMS" id="50" unit="hour" unitType="duration" scale="6.944000051589683E-5" />
        <Cumulative schema="VIMS" id="51" unit="hour" unitType="duration" scale="6.944000051589683E-5" />
        <Cumulative schema="VIMS" id="52" unit="hour" unitType="duration" scale="6.944000051589683E-5" />
        <Cumulative schema="VIMS" id="53" unit="hour" unitType="duration" scale="6.944000051589683E-5" />
        <Cumulative schema="VIMS" id="122" unit="litre" unitType="liquid volume" scale="0.125" />
        <Cumulative schema="VIMS" id="123" unit="litre" unitType="liquid volume" scale="0.125" />
    </CumulativeConfiguration>
    <CumulativeConfiguration model="5130" >
        <Cumulative schema="VIMS" id="33" unit="hour" unitType="duration" scale="6.944000051589683E-5" />
        <Cumulative schema="VIMS" id="42" unit="count" unitType="unitless" scale="1.0" />
        <Cumulative schema="VIMS" id="56" unit="litre" unitType="liquid volume" scale="1.0" />
        <Cumulative schema="VIMS" id="38" unit="litre" unitType="liquid volume" scale="1.0" />
        <Cumulative schema="VIMS" id="9" unit="count" unitType="unitless" scale="1.0" />
    </CumulativeConfiguration>
    <CumulativeConfiguration model="5130B" >
        <Cumulative schema="VIMS" id="33" unit="hour" unitType="duration" scale="6.944000051589683E-5" />
        <Cumulative schema="VIMS" id="42" unit="count" unitType="unitless" scale="1.0" />
        <Cumulative schema="VIMS" id="56" unit="litre" unitType="liquid volume" scale="1.0" />
        <Cumulative schema="VIMS" id="38" unit="litre" unitType="liquid volume" scale="1.0" />
        <Cumulative schema="VIMS" id="9" unit="count" unitType="unitless" scale="1.0" />
        <Cumulative schema="VIMS" id="61" unit="hour" unitType="duration" scale="6.944000051589683E-5" />
    </CumulativeConfiguration>
    <CumulativeConfiguration model="5130C" >
        <Cumulative schema="VIMS" id="116" unit="hour" unitType="duration" scale="1.0" />
        <Cumulative schema="VIMS" id="131" unit="hour" unitType="duration" scale="1.0" />
        <Cumulative schema="VIMS" id="118" unit="hour" unitType="duration" scale="1.0" />
        <Cumulative schema="VIMS" id="120" unit="hour" unitType="duration" scale="1.0" />
        <Cumulative schema="VIMS" id="121" unit="hour" unitType="duration" scale="1.0" />
        <Cumulative schema="VIMS" id="132" unit="count" unitType="unitless" scale="1.0" />
        <Cumulative schema="VIMS" id="33" unit="hour" unitType="duration" scale="6.944000051589683E-5" />
        <Cumulative schema="VIMS" id="42" unit="count" unitType="unitless" scale="1.0" />
        <Cumulative schema="VIMS" id="56" unit="litre" unitType="liquid volume" scale="1.0" />
        <Cumulative schema="VIMS" id="38" unit="litre" unitType="liquid volume" scale="1.0" />
        <Cumulative schema="VIMS" id="9" unit="count" unitType="unitless" scale="1.0" />
        <Cumulative schema="VIMS" id="61" unit="hour" unitType="duration" scale="6.944000051589683E-5" />
        <Cumulative schema="VIMS" id="133" unit="hour" unitType="duration" scale="1.0" />
        <Cumulative schema="VIMS" id="134" unit="hour" unitType="duration" scale="1.0" />
    </CumulativeConfiguration>
    <CumulativeConfiguration model="5230" >
        <Cumulative schema="VIMS" id="33" unit="hour" unitType="duration" scale="6.944000051589683E-5" />
        <Cumulative schema="VIMS" id="42" unit="count" unitType="unitless" scale="1.0" />
        <Cumulative schema="VIMS" id="56" unit="litre" unitType="liquid volume" scale="1.0" />
        <Cumulative schema="VIMS" id="38" unit="litre" unitType="liquid volume" scale="1.0" />
        <Cumulative schema="VIMS" id="9" unit="count" unitType="unitless" scale="1.0" />
        <Cumulative schema="VIMS" id="61" unit="hour" unitType="duration" scale="6.944000051589683E-5" />
    </CumulativeConfiguration>
    <CumulativeConfiguration model="5230B" >
        <Cumulative schema="VIMS" id="33" unit="hour" unitType="duration" scale="6.944000051589683E-5" />
        <Cumulative schema="VIMS" id="42" unit="count" unitType="unitless" scale="1.0" />
        <Cumulative schema="VIMS" id="56" unit="litre" unitType="liquid volume" scale="1.0" />
        <Cumulative schema="VIMS" id="38" unit="litre" unitType="liquid volume" scale="1.0" />
        <Cumulative schema="VIMS" id="9" unit="count" unitType="unitless" scale="1.0" />
        <Cumulative schema="VIMS" id="61" unit="hour" unitType="duration" scale="6.944000051589683E-5" />
        <Cumulative schema="VIMS" id="116" unit="hour" unitType="duration" scale="1.0" />
        <Cumulative schema="VIMS" id="117" unit="hour" unitType="duration" scale="1.0" />
        <Cumulative schema="VIMS" id="118" unit="hour" unitType="duration" scale="1.0" />
        <Cumulative schema="VIMS" id="119" unit="hour" unitType="duration" scale="1.0" />
        <Cumulative schema="VIMS" id="120" unit="hour" unitType="duration" scale="1.0" />
        <Cumulative schema="VIMS" id="121" unit="hour" unitType="duration" scale="1.0" />
        <Cumulative schema="VIMS" id="131" unit="hour" unitType="duration" scale="1.0" />
        <Cumulative schema="VIMS" id="132" unit="count" unitType="unitless" scale="1.0" />
    </CumulativeConfiguration>
    <CumulativeConfiguration model="583T" >
        <Cumulative schema="VIMS" id="3000" unit="hour" unitType="duration" scale="1.0" />
        <Cumulative schema="VIMS" id="3002" unit="hour" unitType="duration" scale="1.0" />
        <Cumulative schema="VIMS" id="3003" unit="hour" unitType="duration" scale="1.0" />
        <Cumulative schema="VIMS" id="3004" unit="hour" unitType="duration" scale="1.0" />
        <Cumulative schema="VIMS" id="3005" unit="hour" unitType="duration" scale="1.0" />
        <Cumulative schema="VIMS" id="3006" unit="hour" unitType="duration" scale="1.0" />
        <Cumulative schema="VIMS" id="3007" unit="hour" unitType="duration" scale="1.0" />
        <Cumulative schema="VIMS" id="3008" unit="hour" unitType="duration" scale="1.0" />
        <Cumulative schema="VIMS" id="3009" unit="hour" unitType="duration" scale="1.0" />
        <Cumulative schema="VIMS" id="3010" unit="mile" unitType="odometer" scale="1.0" />
        <Cumulative schema="VIMS" id="3011" unit="mile" unitType="odometer" scale="1.0" />
        <Cumulative schema="VIMS" id="3012" unit="mile" unitType="odometer" scale="1.0" />
    </CumulativeConfiguration>
    <CumulativeConfiguration model="587T" >
        <Cumulative schema="VIMS" id="3000" unit="hour" unitType="duration" scale="1.0" />
        <Cumulative schema="VIMS" id="3002" unit="hour" unitType="duration" scale="1.0" />
        <Cumulative schema="VIMS" id="3003" unit="hour" unitType="duration" scale="1.0" />
        <Cumulative schema="VIMS" id="3004" unit="hour" unitType="duration" scale="1.0" />
        <Cumulative schema="VIMS" id="3005" unit="hour" unitType="duration" scale="1.0" />
        <Cumulative schema="VIMS" id="3006" unit="hour" unitType="duration" scale="1.0" />
        <Cumulative schema="VIMS" id="3007" unit="hour" unitType="duration" scale="1.0" />
        <Cumulative schema="VIMS" id="3008" unit="hour" unitType="duration" scale="1.0" />
        <Cumulative schema="VIMS" id="3009" unit="hour" unitType="duration" scale="1.0" />
        <Cumulative schema="VIMS" id="3010" unit="mile" unitType="odometer" scale="1.0" />
        <Cumulative schema="VIMS" id="3011" unit="mile" unitType="odometer" scale="1.0" />
        <Cumulative schema="VIMS" id="3012" unit="mile" unitType="odometer" scale="1.0" />
    </CumulativeConfiguration>
    <CumulativeConfiguration model="773E" >
        <Cumulative schema="VIMS" id="10" unit="count" unitType="unitless" scale="1.0" />
        <Cumulative schema="VIMS" id="11" unit="count" unitType="unitless" scale="1.0" />
        <Cumulative schema="VIMS" id="12" unit="count" unitType="unitless" scale="1.0" />
        <Cumulative schema="VIMS" id="13" unit="count" unitType="unitless" scale="1.0" />
        <Cumulative schema="VIMS" id="14" unit="count" unitType="unitless" scale="1.0" />
        <Cumulative schema="VIMS" id="15" unit="count" unitType="unitless" scale="1.0" />
        <Cumulative schema="VIMS" id="24" unit="mile" unitType="odometer" scale="1.0" />
        <Cumulative schema="VIMS" id="25" unit="hour" unitType="duration" scale="6.939999730093405E-5" />
        <Cumulative schema="VIMS" id="26" unit="hour" unitType="duration" scale="6.939999730093405E-5" />
        <Cumulative schema="VIMS" id="27" unit="hour" unitType="duration" scale="6.939999730093405E-5" />
        <Cumulative schema="VIMS" id="28" unit="hour" unitType="duration" scale="6.939999730093405E-5" />
        <Cumulative schema="VIMS" id="29" unit="hour" unitType="duration" scale="6.939999730093405E-5" />
        <Cumulative schema="VIMS" id="30" unit="hour" unitType="duration" scale="6.939999730093405E-5" />
        <Cumulative schema="VIMS" id="31" unit="hour" unitType="duration" scale="6.939999730093405E-5" />
        <Cumulative schema="VIMS" id="32" unit="hour" unitType="duration" scale="6.939999730093405E-5" />
        <Cumulative schema="VIMS" id="33" unit="hour" unitType="duration" scale="6.939999730093405E-5" />
        <Cumulative schema="VIMS" id="135" unit="hour" unitType="duration" scale="6.939999730093405E-5" />
        <Cumulative schema="VIMS" id="136" unit="hour" unitType="duration" scale="6.939999730093405E-5" />
        <Cumulative schema="VIMS" id="42" unit="count" unitType="unitless" scale="1.0" />
        <Cumulative schema="VIMS" id="45" unit="hour" unitType="duration" scale="6.939999730093405E-5" />
        <Cumulative schema="VIMS" id="46" unit="hour" unitType="duration" scale="6.939999730093405E-5" />
        <Cumulative schema="VIMS" id="47" unit="hour" unitType="duration" scale="6.939999730093405E-5" />
        <Cumulative schema="VIMS" id="48" unit="hour" unitType="duration" scale="6.939999730093405E-5" />
        <Cumulative schema="VIMS" id="49" unit="hour" unitType="duration" scale="6.939999730093405E-5" />
        <Cumulative schema="VIMS" id="50" unit="hour" unitType="duration" scale="6.939999730093405E-5" />
        <Cumulative schema="VIMS" id="51" unit="hour" unitType="duration" scale="6.939999730093405E-5" />
        <Cumulative schema="VIMS" id="52" unit="hour" unitType="duration" scale="6.939999730093405E-5" />
        <Cumulative schema="VIMS" id="53" unit="hour" unitType="duration" scale="6.939999730093405E-5" />
        <Cumulative schema="VIMS" id="105" unit="hour" unitType="duration" scale="6.939999730093405E-5" />
        <Cumulative schema="VIMS" id="106" unit="hour" unitType="duration" scale="6.939999730093405E-5" />
    </CumulativeConfiguration>
    <CumulativeConfiguration model="773F" >
        <Cumulative schema="VIMS" id="10" unit="count" unitType="unitless" scale="1.0" />
        <Cumulative schema="VIMS" id="11" unit="count" unitType="unitless" scale="1.0" />
        <Cumulative schema="VIMS" id="12" unit="count" unitType="unitless" scale="1.0" />
        <Cumulative schema="VIMS" id="13" unit="count" unitType="unitless" scale="1.0" />
        <Cumulative schema="VIMS" id="14" unit="count" unitType="unitless" scale="1.0" />
        <Cumulative schema="VIMS" id="15" unit="count" unitType="unitless" scale="1.0" />
        <Cumulative schema="VIMS" id="24" unit="mile" unitType="odometer" scale="1.0" />
        <Cumulative schema="VIMS" id="25" unit="hour" unitType="duration" scale="6.944000051589683E-5" />
        <Cumulative schema="VIMS" id="26" unit="hour" unitType="duration" scale="6.944000051589683E-5" />
        <Cumulative schema="VIMS" id="27" unit="hour" unitType="duration" scale="6.944000051589683E-5" />
        <Cumulative schema="VIMS" id="28" unit="hour" unitType="duration" scale="6.944000051589683E-5" />
        <Cumulative schema="VIMS" id="29" unit="hour" unitType="duration" scale="6.944000051589683E-5" />
        <Cumulative schema="VIMS" id="30" unit="hour" unitType="duration" scale="6.944000051589683E-5" />
        <Cumulative schema="VIMS" id="31" unit="hour" unitType="duration" scale="6.944000051589683E-5" />
        <Cumulative schema="VIMS" id="32" unit="hour" unitType="duration" scale="6.944000051589683E-5" />
        <Cumulative schema="VIMS" id="33" unit="hour" unitType="duration" scale="6.944000051589683E-5" />
        <Cumulative schema="VIMS" id="42" unit="count" unitType="unitless" scale="1.0" />
        <Cumulative schema="VIMS" id="45" unit="hour" unitType="duration" scale="6.944000051589683E-5" />
        <Cumulative schema="VIMS" id="46" unit="hour" unitType="duration" scale="6.944000051589683E-5" />
        <Cumulative schema="VIMS" id="47" unit="hour" unitType="duration" scale="6.944000051589683E-5" />
        <Cumulative schema="VIMS" id="48" unit="hour" unitType="duration" scale="6.944000051589683E-5" />
        <Cumulative schema="VIMS" id="49" unit="hour" unitType="duration" scale="6.944000051589683E-5" />
        <Cumulative schema="VIMS" id="50" unit="hour" unitType="duration" scale="6.944000051589683E-5" />
        <Cumulative schema="VIMS" id="51" unit="hour" unitType="duration" scale="6.944000051589683E-5" />
        <Cumulative schema="VIMS" id="52" unit="hour" unitType="duration" scale="6.944000051589683E-5" />
        <Cumulative schema="VIMS" id="53" unit="hour" unitType="duration" scale="6.944000051589683E-5" />
        <Cumulative schema="VIMS" id="105" unit="hour" unitType="duration" scale="6.944000051589683E-5" />
        <Cumulative schema="VIMS" id="135" unit="hour" unitType="duration" scale="6.944000051589683E-5" />
    </CumulativeConfiguration>
    <CumulativeConfiguration model="773G" >
        <Cumulative schema="VIMS" id="10" unit="count" unitType="unitless" scale="1.0" />
        <Cumulative schema="VIMS" id="11" unit="count" unitType="unitless" scale="1.0" />
        <Cumulative schema="VIMS" id="12" unit="count" unitType="unitless" scale="1.0" />
        <Cumulative schema="VIMS" id="13" unit="count" unitType="unitless" scale="1.0" />
        <Cumulative schema="VIMS" id="14" unit="count" unitType="unitless" scale="1.0" />
        <Cumulative schema="VIMS" id="15" unit="count" unitType="unitless" scale="1.0" />
        <Cumulative schema="VIMS" id="24" unit="mile" unitType="odometer" scale="1.0" />
        <Cumulative schema="VIMS" id="25" unit="hour" unitType="duration" scale="6.939999730093405E-5" />
        <Cumulative schema="VIMS" id="26" unit="hour" unitType="duration" scale="6.939999730093405E-5" />
        <Cumulative schema="VIMS" id="27" unit="hour" unitType="duration" scale="6.939999730093405E-5" />
        <Cumulative schema="VIMS" id="28" unit="hour" unitType="duration" scale="6.939999730093405E-5" />
        <Cumulative schema="VIMS" id="29" unit="hour" unitType="duration" scale="6.939999730093405E-5" />
        <Cumulative schema="VIMS" id="30" unit="hour" unitType="duration" scale="6.939999730093405E-5" />
        <Cumulative schema="VIMS" id="31" unit="hour" unitType="duration" scale="6.939999730093405E-5" />
        <Cumulative schema="VIMS" id="32" unit="hour" unitType="duration" scale="6.939999730093405E-5" />
        <Cumulative schema="VIMS" id="33" unit="hour" unitType="duration" scale="6.939999730093405E-5" />
        <Cumulative schema="VIMS" id="135" unit="hour" unitType="duration" scale="6.939999730093405E-5" />
        <Cumulative schema="VIMS" id="42" unit="count" unitType="unitless" scale="1.0" />
        <Cumulative schema="VIMS" id="45" unit="hour" unitType="duration" scale="6.939999730093405E-5" />
        <Cumulative schema="VIMS" id="46" unit="hour" unitType="duration" scale="6.939999730093405E-5" />
        <Cumulative schema="VIMS" id="47" unit="hour" unitType="duration" scale="6.939999730093405E-5" />
        <Cumulative schema="VIMS" id="48" unit="hour" unitType="duration" scale="6.939999730093405E-5" />
        <Cumulative schema="VIMS" id="49" unit="hour" unitType="duration" scale="6.939999730093405E-5" />
        <Cumulative schema="VIMS" id="50" unit="hour" unitType="duration" scale="6.939999730093405E-5" />
        <Cumulative schema="VIMS" id="51" unit="hour" unitType="duration" scale="6.939999730093405E-5" />
        <Cumulative schema="VIMS" id="52" unit="hour" unitType="duration" scale="6.939999730093405E-5" />
        <Cumulative schema="VIMS" id="53" unit="hour" unitType="duration" scale="6.939999730093405E-5" />
        <Cumulative schema="VIMS" id="105" unit="hour" unitType="duration" scale="6.939999730093405E-5" />
        <Cumulative schema="VIMS" id="106" unit="hour" unitType="duration" scale="6.939999730093405E-5" />
    </CumulativeConfiguration>
    <CumulativeConfiguration model="773G LRC" >
        <Cumulative schema="VIMS" id="10" unit="count" unitType="unitless" scale="1.0" />
        <Cumulative schema="VIMS" id="11" unit="count" unitType="unitless" scale="1.0" />
        <Cumulative schema="VIMS" id="12" unit="count" unitType="unitless" scale="1.0" />
        <Cumulative schema="VIMS" id="13" unit="count" unitType="unitless" scale="1.0" />
        <Cumulative schema="VIMS" id="14" unit="count" unitType="unitless" scale="1.0" />
        <Cumulative schema="VIMS" id="15" unit="count" unitType="unitless" scale="1.0" />
        <Cumulative schema="VIMS" id="24" unit="mile" unitType="odometer" scale="1.0" />
        <Cumulative schema="VIMS" id="25" unit="hour" unitType="duration" scale="6.939999730093405E-5" />
        <Cumulative schema="VIMS" id="26" unit="hour" unitType="duration" scale="6.939999730093405E-5" />
        <Cumulative schema="VIMS" id="27" unit="hour" unitType="duration" scale="6.939999730093405E-5" />
        <Cumulative schema="VIMS" id="28" unit="hour" unitType="duration" scale="6.939999730093405E-5" />
        <Cumulative schema="VIMS" id="29" unit="hour" unitType="duration" scale="6.939999730093405E-5" />
        <Cumulative schema="VIMS" id="30" unit="hour" unitType="duration" scale="6.939999730093405E-5" />
        <Cumulative schema="VIMS" id="31" unit="hour" unitType="duration" scale="6.939999730093405E-5" />
        <Cumulative schema="VIMS" id="32" unit="hour" unitType="duration" scale="6.939999730093405E-5" />
        <Cumulative schema="VIMS" id="33" unit="hour" unitType="duration" scale="6.939999730093405E-5" />
        <Cumulative schema="VIMS" id="135" unit="hour" unitType="duration" scale="6.939999730093405E-5" />
        <Cumulative schema="VIMS" id="42" unit="count" unitType="unitless" scale="1.0" />
        <Cumulative schema="VIMS" id="45" unit="hour" unitType="duration" scale="6.939999730093405E-5" />
        <Cumulative schema="VIMS" id="46" unit="hour" unitType="duration" scale="6.939999730093405E-5" />
        <Cumulative schema="VIMS" id="47" unit="hour" unitType="duration" scale="6.939999730093405E-5" />
        <Cumulative schema="VIMS" id="48" unit="hour" unitType="duration" scale="6.939999730093405E-5" />
        <Cumulative schema="VIMS" id="49" unit="hour" unitType="duration" scale="6.939999730093405E-5" />
        <Cumulative schema="VIMS" id="50" unit="hour" unitType="duration" scale="6.939999730093405E-5" />
        <Cumulative schema="VIMS" id="51" unit="hour" unitType="duration" scale="6.939999730093405E-5" />
        <Cumulative schema="VIMS" id="52" unit="hour" unitType="duration" scale="6.939999730093405E-5" />
        <Cumulative schema="VIMS" id="53" unit="hour" unitType="duration" scale="6.939999730093405E-5" />
        <Cumulative schema="VIMS" id="105" unit="hour" unitType="duration" scale="6.939999730093405E-5" />
        <Cumulative schema="VIMS" id="106" unit="hour" unitType="duration" scale="6.939999730093405E-5" />
    </CumulativeConfiguration>
    <CumulativeConfiguration model="775F" >
        <Cumulative schema="VIMS" id="10" unit="count" unitType="unitless" scale="1.0" />
        <Cumulative schema="VIMS" id="11" unit="count" unitType="unitless" scale="1.0" />
        <Cumulative schema="VIMS" id="12" unit="count" unitType="unitless" scale="1.0" />
        <Cumulative schema="VIMS" id="13" unit="count" unitType="unitless" scale="1.0" />
        <Cumulative schema="VIMS" id="14" unit="count" unitType="unitless" scale="1.0" />
        <Cumulative schema="VIMS" id="15" unit="count" unitType="unitless" scale="1.0" />
        <Cumulative schema="VIMS" id="24" unit="mile" unitType="odometer" scale="1.0" />
        <Cumulative schema="VIMS" id="25" unit="hour" unitType="duration" scale="6.944000051589683E-5" />
        <Cumulative schema="VIMS" id="26" unit="hour" unitType="duration" scale="6.944000051589683E-5" />
        <Cumulative schema="VIMS" id="27" unit="hour" unitType="duration" scale="6.944000051589683E-5" />
        <Cumulative schema="VIMS" id="28" unit="hour" unitType="duration" scale="6.944000051589683E-5" />
        <Cumulative schema="VIMS" id="29" unit="hour" unitType="duration" scale="6.944000051589683E-5" />
        <Cumulative schema="VIMS" id="30" unit="hour" unitType="duration" scale="6.944000051589683E-5" />
        <Cumulative schema="VIMS" id="31" unit="hour" unitType="duration" scale="6.944000051589683E-5" />
        <Cumulative schema="VIMS" id="32" unit="hour" unitType="duration" scale="6.944000051589683E-5" />
        <Cumulative schema="VIMS" id="33" unit="hour" unitType="duration" scale="6.944000051589683E-5" />
        <Cumulative schema="VIMS" id="42" unit="count" unitType="unitless" scale="1.0" />
        <Cumulative schema="VIMS" id="45" unit="hour" unitType="duration" scale="6.944000051589683E-5" />
        <Cumulative schema="VIMS" id="46" unit="hour" unitType="duration" scale="6.944000051589683E-5" />
        <Cumulative schema="VIMS" id="47" unit="hour" unitType="duration" scale="6.944000051589683E-5" />
        <Cumulative schema="VIMS" id="48" unit="hour" unitType="duration" scale="6.944000051589683E-5" />
        <Cumulative schema="VIMS" id="49" unit="hour" unitType="duration" scale="6.944000051589683E-5" />
        <Cumulative schema="VIMS" id="50" unit="hour" unitType="duration" scale="6.944000051589683E-5" />
        <Cumulative schema="VIMS" id="51" unit="hour" unitType="duration" scale="6.944000051589683E-5" />
        <Cumulative schema="VIMS" id="52" unit="hour" unitType="duration" scale="6.944000051589683E-5" />
        <Cumulative schema="VIMS" id="53" unit="hour" unitType="duration" scale="6.944000051589683E-5" />
        <Cumulative schema="VIMS" id="105" unit="hour" unitType="duration" scale="6.944000051589683E-5" />
        <Cumulative schema="VIMS" id="135" unit="hour" unitType="duration" scale="6.944000051589683E-5" />
    </CumulativeConfiguration>
    <CumulativeConfiguration model="775G" >
        <Cumulative schema="VIMS" id="10" unit="count" unitType="unitless" scale="1.0" />
        <Cumulative schema="VIMS" id="11" unit="count" unitType="unitless" scale="1.0" />
        <Cumulative schema="VIMS" id="12" unit="count" unitType="unitless" scale="1.0" />
        <Cumulative schema="VIMS" id="13" unit="count" unitType="unitless" scale="1.0" />
        <Cumulative schema="VIMS" id="14" unit="count" unitType="unitless" scale="1.0" />
        <Cumulative schema="VIMS" id="15" unit="count" unitType="unitless" scale="1.0" />
        <Cumulative schema="VIMS" id="24" unit="mile" unitType="odometer" scale="1.0" />
        <Cumulative schema="VIMS" id="25" unit="hour" unitType="duration" scale="6.939999730093405E-5" />
        <Cumulative schema="VIMS" id="26" unit="hour" unitType="duration" scale="6.939999730093405E-5" />
        <Cumulative schema="VIMS" id="27" unit="hour" unitType="duration" scale="6.939999730093405E-5" />
        <Cumulative schema="VIMS" id="28" unit="hour" unitType="duration" scale="6.939999730093405E-5" />
        <Cumulative schema="VIMS" id="29" unit="hour" unitType="duration" scale="6.939999730093405E-5" />
        <Cumulative schema="VIMS" id="30" unit="hour" unitType="duration" scale="6.939999730093405E-5" />
        <Cumulative schema="VIMS" id="31" unit="hour" unitType="duration" scale="6.939999730093405E-5" />
        <Cumulative schema="VIMS" id="32" unit="hour" unitType="duration" scale="6.939999730093405E-5" />
        <Cumulative schema="VIMS" id="33" unit="hour" unitType="duration" scale="6.939999730093405E-5" />
        <Cumulative schema="VIMS" id="135" unit="hour" unitType="duration" scale="6.939999730093405E-5" />
        <Cumulative schema="VIMS" id="42" unit="count" unitType="unitless" scale="1.0" />
        <Cumulative schema="VIMS" id="45" unit="hour" unitType="duration" scale="6.939999730093405E-5" />
        <Cumulative schema="VIMS" id="46" unit="hour" unitType="duration" scale="6.939999730093405E-5" />
        <Cumulative schema="VIMS" id="47" unit="hour" unitType="duration" scale="6.939999730093405E-5" />
        <Cumulative schema="VIMS" id="48" unit="hour" unitType="duration" scale="6.939999730093405E-5" />
        <Cumulative schema="VIMS" id="49" unit="hour" unitType="duration" scale="6.939999730093405E-5" />
        <Cumulative schema="VIMS" id="50" unit="hour" unitType="duration" scale="6.939999730093405E-5" />
        <Cumulative schema="VIMS" id="51" unit="hour" unitType="duration" scale="6.939999730093405E-5" />
        <Cumulative schema="VIMS" id="52" unit="hour" unitType="duration" scale="6.939999730093405E-5" />
        <Cumulative schema="VIMS" id="53" unit="hour" unitType="duration" scale="6.939999730093405E-5" />
        <Cumulative schema="VIMS" id="105" unit="hour" unitType="duration" scale="6.939999730093405E-5" />
        <Cumulative schema="VIMS" id="106" unit="hour" unitType="duration" scale="6.939999730093405E-5" />
    </CumulativeConfiguration>
    <CumulativeConfiguration model="775G LRC" >
        <Cumulative schema="VIMS" id="10" unit="count" unitType="unitless" scale="1.0" />
        <Cumulative schema="VIMS" id="11" unit="count" unitType="unitless" scale="1.0" />