<?xml version="1.0" standalone="no"?>
<!DOCTYPE TrendConfigurations [
<!ELEMENT TrendConfigurations (TrendConfiguration)+>
<!ELEMENT TrendConfiguration (Trend)+>
<!ATTLIST TrendConfiguration
model CDATA #REQUIRED
>
<!ELEMENT Trend EMPTY>
<!ATTLIST Trend
schema CDATA #REQUIRED
id CDATA #REQUIRED
>
]>
<TrendConfigurations>
    <TrendConfiguration model="200CII" >
        <Trend schema="VIMS" id="7" />
        <Trend schema="VIMS" id="12" />
        <Trend schema="VIMS" id="26" />
        <Trend schema="VIMS" id="37" />
        <Trend schema="VIMS" id="38" />
        <Trend schema="VIMS" id="43" />
        <Trend schema="VIMS" id="71" />
        <Trend schema="VIMS" id="72" />
        <Trend schema="VIMS" id="73" />
        <Trend schema="VIMS" id="74" />
        <Trend schema="VIMS" id="75" />
        <Trend schema="VIMS" id="76" />
        <Trend schema="VIMS" id="78" />
        <Trend schema="VIMS" id="105" />
        <Trend schema="VIMS" id="106" />
        <Trend schema="VIMS" id="107" />
        <Trend schema="VIMS" id="113" />
        <Trend schema="VIMS" id="192" />
        <Trend schema="VIMS" id="193" />
        <Trend schema="VIMS" id="197" />
        <Trend schema="VIMS" id="198" />
        <Trend schema="VIMS" id="199" />
        <Trend schema="VIMS" id="200" />
        <Trend schema="VIMS" id="281" />
        <Trend schema="VIMS" id="282" />
        <Trend schema="VIMS" id="373" />
        <Trend schema="VIMS" id="374" />
        <Trend schema="VIMS" id="377" />
        <Trend schema="VIMS" id="378" />
        <Trend schema="VIMS" id="379" />
        <Trend schema="VIMS" id="380" />
    </TrendConfiguration>
    <TrendConfiguration model="5130" >
        <Trend schema="VIMS" id="5" />
        <Trend schema="VIMS" id="10" />
        <Trend schema="VIMS" id="15" />
        <Trend schema="VIMS" id="22" />
        <Trend schema="VIMS" id="29" />
        <Trend schema="VIMS" id="33" />
        <Trend schema="VIMS" id="42" />
        <Trend schema="VIMS" id="45" />
        <Trend schema="VIMS" id="59" />
        <Trend schema="VIMS" id="93" />
    </TrendConfiguration>
    <TrendConfiguration model="5130B" >
        <Trend schema="VIMS" id="4" />
        <Trend schema="VIMS" id="5" />
        <Trend schema="VIMS" id="9" />
        <Trend schema="VIMS" id="10" />
        <Trend schema="VIMS" id="14" />
        <Trend schema="VIMS" id="15" />
        <Trend schema="VIMS" id="21" />
        <Trend schema="VIMS" id="22" />
        <Trend schema="VIMS" id="28" />
        <Trend schema="VIMS" id="29" />
        <Trend schema="VIMS" id="41" />
        <Trend schema="VIMS" id="42" />
        <Trend schema="VIMS" id="44" />
        <Trend schema="VIMS" id="45" />
        <Trend schema="VIMS" id="58" />
        <Trend schema="VIMS" id="59" />
        <Trend schema="VIMS" id="91" />
        <Trend schema="VIMS" id="92" />
    </TrendConfiguration>
    <TrendConfiguration model="5230" >
        <Trend schema="VIMS" id="5" />
        <Trend schema="VIMS" id="10" />
        <Trend schema="VIMS" id="15" />
        <Trend schema="VIMS" id="22" />
        <Trend schema="VIMS" id="29" />
        <Trend schema="VIMS" id="42" />
        <Trend schema="VIMS" id="45" />
        <Trend schema="VIMS" id="59" />
        <Trend schema="VIMS" id="93" />
    </TrendConfiguration>
    <TrendConfiguration model="5230B" >
        <Trend schema="VIMS" id="2" />
        <Trend schema="VIMS" id="7" />
        <Trend schema="VIMS" id="12" />
        <Trend schema="VIMS" id="26" />
        <Trend schema="VIMS" id="43" />
        <Trend schema="VIMS" id="123" />
        <Trend schema="VIMS" id="200" />
        <Trend schema="VIMS" id="207" />
        <Trend schema="VIMS" id="208" />
        <Trend schema="VIMS" id="212" />
        <Trend schema="VIMS" id="213" />
        <Trend schema="VIMS" id="222" />
        <Trend schema="VIMS" id="267" />
        <Trend schema="VIMS" id="268" />
        <Trend schema="VIMS" id="269" />
        <Trend schema="VIMS" id="270" />
        <Trend schema="VIMS" id="271" />
        <Trend schema="VIMS" id="272" />
        <Trend schema="VIMS" id="279" />
        <Trend schema="VIMS" id="280" />
    </TrendConfiguration>
    <TrendConfiguration model="770G_LRC" >
        <Trend schema="VIMS" id="532" />
        <Trend schema="VIMS" id="533" />
    </TrendConfiguration>
    <TrendConfiguration model="772G_LRC" >
        <Trend schema="VIMS" id="532" />
        <Trend schema="VIMS" id="533" />
    </TrendConfiguration>
    <TrendConfiguration model="773E" >
        <Trend schema="VIMS" id="2" />
        <Trend schema="VIMS" id="7" />
        <Trend schema="VIMS" id="12" />
        <Trend schema="VIMS" id="26" />
        <Trend schema="VIMS" id="37" />
        <Trend schema="VIMS" id="103" />
        <Trend schema="VIMS" id="105" />
        <Trend schema="VIMS" id="113" />
        <Trend schema="VIMS" id="178" />
        <Trend schema="VIMS" id="179" />
        <Trend schema="VIMS" id="182" />
        <Trend schema="VIMS" id="185" />
        <Trend schema="VIMS" id="198" />
        <Trend schema="VIMS" id="199" />
        <Trend schema="VIMS" id="200" />
        <Trend schema="VIMS" id="220" />
        <Trend schema="VIMS" id="221" />
        <Trend schema="VIMS" id="299" />
        <Trend schema="VIMS" id="300" />
        <Trend schema="VIMS" id="301" />
        <Trend schema="VIMS" id="370" />
        <Trend schema="VIMS" id="373" />
        <Trend schema="VIMS" id="374" />
        <Trend schema="VIMS" id="375" />
    </TrendConfiguration>
    <TrendConfiguration model="773F" >
        <Trend schema="VIMS" id="7" />
        <Trend schema="VIMS" id="12" />
        <Trend schema="VIMS" id="13" />
        <Trend schema="VIMS" id="20" />
        <Trend schema="VIMS" id="26" />
        <Trend schema="VIMS" id="27" />
        <Trend schema="VIMS" id="32" />
        <Trend schema="VIMS" id="37" />
        <Trend schema="VIMS" id="38" />
        <Trend schema="VIMS" id="51" />
        <Trend schema="VIMS" id="53" />
        <Trend schema="VIMS" id="70" />
        <Trend schema="VIMS" id="103" />
        <Trend schema="VIMS" id="105" />
        <Trend schema="VIMS" id="178" />
        <Trend schema="VIMS" id="179" />
        <Trend schema="VIMS" id="182" />
        <Trend schema="VIMS" id="185" />
        <Trend schema="VIMS" id="198" />
        <Trend schema="VIMS" id="199" />
        <Trend schema="VIMS" id="200" />
        <Trend schema="VIMS" id="220" />
        <Trend schema="VIMS" id="221" />
        <Trend schema="VIMS" id="299" />
        <Trend schema="VIMS" id="300" />
        <Trend schema="VIMS" id="301" />
        <Trend schema="VIMS" id="375" />
        <Trend schema="VIMS" id="376" />
        <Trend schema="VIMS" id="377" />
        <Trend schema="VIMS" id="378" />
        <Trend schema="VIMS" id="379" />
        <Trend schema="VIMS" id="380" />
        <Trend schema="VIMS" id="437" />
    </TrendConfiguration>
    <TrendConfiguration model="773G" >
        <Trend schema="VIMS" id="13" />
        <Trend schema="VIMS" id="20" />
        <Trend schema="VIMS" id="27" />
        <Trend schema="VIMS" id="32" />
        <Trend schema="VIMS" id="38" />
        <Trend schema="VIMS" id="51" />
        <Trend schema="VIMS" id="53" />
        <Trend schema="VIMS" id="70" />
        <Trend schema="VIMS" id="77" />
        <Trend schema="VIMS" id="79" />
        <Trend schema="VIMS" id="103" />
        <Trend schema="VIMS" id="105" />
        <Trend schema="VIMS" id="113" />
        <Trend schema="VIMS" id="192" />
        <Trend schema="VIMS" id="193" />
        <Trend schema="VIMS" id="194" />
        <Trend schema="VIMS" id="195" />
        <Trend schema="VIMS" id="196" />
        <Trend schema="VIMS" id="197" />
        <Trend schema="VIMS" id="198" />
        <Trend schema="VIMS" id="199" />
        <Trend schema="VIMS" id="220" />
        <Trend schema="VIMS" id="221" />
        <Trend schema="VIMS" id="299" />
        <Trend schema="VIMS" id="300" />
        <Trend schema="VIMS" id="301" />
        <Trend schema="VIMS" id="375" />
        <Trend schema="VIMS" id="376" />
        <Trend schema="VIMS" id="377" />
        <Trend schema="VIMS" id="378" />
        <Trend schema="VIMS" id="379" />
        <Trend schema="VIMS" id="380" />
        <Trend schema="VIMS" id="381" />
        <Trend schema="VIMS" id="382" />
        <Trend schema="VIMS" id="384" />
        <Trend schema="VIMS" id="385" />
        <Trend schema="VIMS" id="386" />
        <Trend schema="VIMS" id="387" />
        <Trend schema="VIMS" id="388" />
        <Trend schema="VIMS" id="389" />
        <Trend schema="VIMS" id="401" />
        <Trend schema="VIMS" id="402" />
        <Trend schema="VIMS" id="403" />
        <Trend schema="VIMS" id="404" />
        <Trend schema="VIMS" id="532" />
        <Trend schema="VIMS" id="533" />
    </TrendConfiguration>
    <TrendConfiguration model="773G LRC" >
        <Trend schema="VIMS" id="13" />
        <Trend schema="VIMS" id="20" />
        <Trend schema="VIMS" id="27" />
        <Trend schema="VIMS" id="32" />
        <Trend schema="VIMS" id="38" />
        <Trend schema="VIMS" id="51" />
        <Trend schema="VIMS" id="53" />
        <Trend schema="VIMS" id="70" />
        <Trend schema="VIMS" id="77" />
        <Trend schema="VIMS" id="79" />
        <Trend schema="VIMS" id="103" />
        <Trend schema="VIMS" id="105" />
        <Trend schema="VIMS" id="113" />
        <Trend schema="VIMS" id="192" />
        <Trend schema="VIMS" id="193" />
        <Trend schema="VIMS" id="194" />
        <Trend schema="VIMS" id="195" />
        <Trend schema="VIMS" id="196" />
        <Trend schema="VIMS" id="197" />
        <Trend schema="VIMS" id="198" />
        <Trend schema="VIMS" id="199" />
        <Trend schema="VIMS" id="220" />
        <Trend schema="VIMS" id="221" />
        <Trend schema="VIMS" id="299" />
        <Trend schema="VIMS" id="300" />
        <Trend schema="VIMS" id="301" />
        <Trend schema="VIMS" id="375" />
        <Trend schema="VIMS" id="376" />
        <Trend schema="VIMS" id="377" />
        <Trend schema="VIMS" id="378" />
        <Trend schema="VIMS" id="379" />
        <Trend schema="VIMS" id="380" />
        <Trend schema="VIMS" id="381" />
        <Trend schema="VIMS" id="382" />
        <Trend schema="VIMS" id="384" />
        <Trend schema="VIMS" id="385" />
        <Trend schema="VIMS" id="386" />
        <Trend schema="VIMS" id="387" />
        <Trend schema="VIMS" id="388" />
        <Trend schema="VIMS" id="389" />
        <Trend schema="VIMS" id="401" />
        <Trend schema="VIMS" id="402" />
        <Trend schema="VIMS" id="403" />
        <Trend schema="VIMS" id="404" />
        <Trend schema="VIMS" id="532" />
        <Trend schema="VIMS" id="533" />
    </TrendConfiguration>
    <TrendConfiguration model="775F" >
        <Trend schema="VIMS" id="7" />
        <Trend schema="VIMS" id="12" />
        <Trend schema="VIMS" id="13" />
        <Trend schema="VIMS" id="20" />
        <Trend schema="VIMS" id="26" />
        <Trend schema="VIMS" id="27" />
        <Trend schema="VIMS" id="32" />
        <Trend schema="VIMS" id="37" />
        <Trend schema="VIMS" id="38" />
        <Trend schema="VIMS" id="51" />
        <Trend schema="VIMS" id="53" />
        <Trend schema="VIMS" id="70" />
        <Trend schema="VIMS" id="103" />
        <Trend schema="VIMS" id="105" />
        <Trend schema="VIMS" id="178" />
        <Trend schema="VIMS" id="179" />
        <Trend schema="VIMS" id="182" />
        <Trend schema="VIMS" id="185" />
        <Trend schema="VIMS" id="198" />
        <Trend schema="VIMS" id="199" />
        <Trend schema="VIMS" id="200" />
        <Trend schema="VIMS" id="220" />
        <Trend schema="VIMS" id="221" />
        <Trend schema="VIMS" id="299" />
        <Trend schema="VIMS" id="300" />
        <Trend schema="VIMS" id="301" />
        <Trend schema="VIMS" id="375" />
        <Trend schema="VIMS" id="376" />
        <Trend schema="VIMS" id="377" />
        <Trend schema="VIMS" id="378" />
        <Trend schema="VIMS" id="379" />
        <Trend schema="VIMS" id="380" />
        <Trend schema="VIMS" id="437" />
    </TrendConfiguration>
    <TrendConfiguration model="775G" >
        <Trend schema="VIMS" id="13" />
        <Trend schema="VIMS" id="20" />
        <Trend schema="VIMS" id="27" />
        <Trend schema="VIMS" id="32" />
        <Trend schema="VIMS" id="38" />
        <Trend schema="VIMS" id="51" />
        <Trend schema="VIMS" id="53" />
        <Trend schema="VIMS" id="70" />
        <Trend schema="VIMS" id="77" />
        <Trend schema="VIMS" id="79" />
        <Trend schema="VIMS" id="103" />
        <Trend schema="VIMS" id="105" />
        <Trend schema="VIMS" id="113" />
        <Trend schema="VIMS" id="192" />
        <Trend schema="VIMS" id="193" />
        <Trend schema="VIMS" id="194" />
        <Trend schema="VIMS" id="195" />
        <Trend schema="VIMS" id="196" />
        <Trend schema="VIMS" id="197" />
        <Trend schema="VIMS" id="198" />
        <Trend schema="VIMS" id="199" />
        <Trend schema="VIMS" id="220" />
        <Trend schema="VIMS" id="221" />
        <Trend schema="VIMS" id="299" />
        <Trend schema="VIMS" id="300" />
        <Trend schema="VIMS" id="301" />
        <Trend schema="VIMS" id="375" />
        <Trend schema="VIMS" id="376" />
        <Trend schema="VIMS" id="377" />
        <Trend schema="VIMS" id="378" />
        <Trend schema="VIMS" id="379" />
        <Trend schema="VIMS" id="380" />
        <Trend schema="VIMS" id="381" />
        <Trend schema="VIMS" id="382" />
        <Trend schema="VIMS" id="384" />
        <Trend schema="VIMS" id="385" />
        <Trend schema="VIMS" id="386" />
        <Trend schema="VIMS" id="387" />
        <Trend schema="VIMS" id="388" />
        <Trend schema="VIMS" id="389" />
        <Trend schema="VIMS" id="401" />
        <Trend schema="VIMS" id="402" />
        <Trend schema="VIMS" id="403" />
        <Trend schema="VIMS" id="404" />
        <Trend schema="VIMS" id="532" />
        <Trend schema="VIMS" id="533" />
    </TrendConfiguration>
    <TrendConfiguration model="775G LRC" >
        <Trend schema="VIMS" id="83" />
        <Trend schema="VIMS" id="103" />
        <Trend schema="VIMS" id="105" />
        <Trend schema="VIMS" id="113" />
        <Trend schema="VIMS" id="192" />
        <Trend schema="VIMS" id="193" />
        <Trend schema="VIMS" id="194" />
        <Trend schema="VIMS" id="195" />
        <Trend schema="VIMS" id="198" />
        <Trend schema="VIMS" id="199" />
        <Trend schema="VIMS" id="216" />
        <Trend schema="VIMS" id="217" />
        <Trend schema="VIMS" id="218" />
        <Trend schema="VIMS" id="219" />
        <Trend schema="VIMS" id="220" />
        <Trend schema="VIMS" id="221" />
        <Trend schema="VIMS" id="299" />
        <Trend schema="VIMS" id="300" />
        <Trend schema="VIMS" id="301" />
        <Trend schema="VIMS" id="401" />
        <Trend schema="VIMS" id="402" />
        <Trend schema="VIMS" id="403" />
        <Trend schema="VIMS" id="404" />
        <Trend schema="VIMS" id="437" />
        <Trend schema="VIMS" id="487" />
        <Trend schema="VIMS" id="488" />
        <Trend schema="VIMS" id="489" />
        <Trend schema="VIMS" id="490" />
        <Trend schema="VIMS" id="491" />
        <Trend schema="VIMS" id="492" />
        <Trend schema="VIMS" id="493" />
        <Trend schema="VIMS" id="494" />
        <Trend schema="VIMS" id="532" />
        <Trend schema="VIMS" id="533" />
    </TrendConfiguration>
    <TrendConfiguration model="776D" >
        <Trend schema="VIMS" id="7" />
        <Trend schema="VIMS" id="12" />
        <Trend schema="VIMS" id="26" />
        <Trend schema="VIMS" id="37" />
        <Trend schema="VIMS" id="38" />
        <Trend schema="VIMS" id="103" />
        <Trend schema="VIMS" id="105" />
        <Trend schema="VIMS" id="113" />
        <Trend schema="VIMS" id="178" />
        <Trend schema="VIMS" id="179" />
        <Trend schema="VIMS" id="182" />
        <Trend schema="VIMS" id="185" />
        <Trend schema="VIMS" id="198" />
        <Trend schema="VIMS" id="199" />
        <Trend schema="VIMS" id="200" />
        <Trend schema="VIMS" id="220" />
        <Trend schema="VIMS" id="221" />
        <Trend schema="VIMS" id="299" />
        <Trend schema="VIMS" id="300" />
        <Trend schema="VIMS" id="301" />
        <Trend schema="VIMS" id="340" />
        <Trend schema="VIMS" id="373" />
        <Trend schema="VIMS" id="374" />
        <Trend schema="VIMS" id="375" />
    </TrendConfiguration>
    <TrendConfiguration model="777D" >
        <Trend schema="VIMS" id="7" />
        <Trend schema="VIMS" id="12" />
        <Trend schema="VIMS" id="26" />
        <Trend schema="VIMS" id="37" />
        <Trend schema="VIMS" id="38" />
        <Trend schema="VIMS" id="71" />
        <Trend schema="VIMS" id="72" />
        <Trend schema="VIMS" id="73" />
        <Trend schema="VIMS" id="74" />
        <Trend schema="VIMS" id="75" />
        <Trend schema="VIMS" id="76" />
        <Trend schema="VIMS" id="78" />
        <Trend schema="VIMS" id="103" />
        <Trend schema="VIMS" id="105" />
        <Trend schema="VIMS" id="113" />
        <Trend schema="VIMS" id="178" />
        <Trend schema="VIMS" id="179" />
        <Trend schema="VIMS" id="182" />
        <Trend schema="VIMS" id="185" />
        <Trend schema="VIMS" id="198" />
        <Trend schema="VIMS" id="199" />
        <Trend schema="VIMS" id="200" />
        <Trend schema="VIMS" id="220" />
        <Trend schema="VIMS" id="221" />
        <Trend schema="VIMS" id="299" />
        <Trend schema="VIMS" id="300" />
        <Trend schema="VIMS" id="301" />
        <Trend schema="VIMS" id="302" />
        <Trend schema="VIMS" id="303" />
        <Trend schema="VIMS" id="340" />
        <Trend schema="VIMS" id="366" />
        <Trend schema="VIMS" id="370" />
        <Trend schema="VIMS" id="373" />
        <Trend schema="VIMS" id="374" />
        <Trend schema="VIMS" id="375" />
    </TrendConfiguration>
    <TrendConfiguration model="777F" >
        <Trend schema="VIMS" id="7" />
        <Trend schema="VIMS" id="12" />
        <Trend schema="VIMS" id="13" />
        <Trend schema="VIMS" id="20" />
        <Trend schema="VIMS" id="26" />
        <Trend schema="VIMS" id="27" />
        <Trend schema="VIMS" id="32" />
        <Trend schema="VIMS" id="37" />
        <Trend schema="VIMS" id="38" />
        <Trend schema="VIMS" id="51" />
        <Trend schema="VIMS" id="53" />
        <Trend schema="VIMS" id="70" />
        <Trend schema="VIMS" id="77" />
        <Trend schema="VIMS" id="79" />
        <Trend schema="VIMS" id="103" />
        <Trend schema="VIMS" id="105" />
        <Trend schema="VIMS" id="113" />
        <Trend schema="VIMS" id="178" />
        <Trend schema="VIMS" id="179" />
        <Trend schema="VIMS" id="182" />
        <Trend schema="VIMS" id="185" />
        <Trend schema="VIMS" id="192" />
        <Trend schema="VIMS" id="193" />
        <Trend schema="VIMS" id="194" />
        <Trend schema="VIMS" id="195" />
        <Trend schema="VIMS" id="196" />
        <Trend schema="VIMS" id="197" />
        <Trend schema="VIMS" id="198" />
        <Trend schema="VIMS" id="199" />
        <Trend schema="VIMS" id="200" />
        <Trend schema="VIMS" id="220" />
        <Trend schema="VIMS" id="221" />
        <Trend schema="VIMS" id="299" />
        <Trend schema="VIMS" id="300" />
        <Trend schema="VIMS" id="301" />
        <Trend schema="VIMS" id="373" />
        <Trend schema="VIMS" id="374" />
        <Trend schema="VIMS" id="375" />
        <Trend schema="VIMS" id="376" />
        <Trend schema="VIMS" id="377" />
        <Trend schema="VIMS" id="378" />
        <Trend schema="VIMS" id="379" />
        <Trend schema="VIMS" id="380" />
        <Trend schema="VIMS" id="381" />
        <Trend schema="VIMS" id="382" />
        <Trend schema="VIMS" id="384" />
        <Trend schema="VIMS" id="385" />
        <Trend schema="VIMS" id="386" />
        <Trend schema="VIMS" id="387" />
        <Trend schema="VIMS" id="388" />
        <Trend schema="VIMS" id="389" />
        <Trend schema="VIMS" id="401" />
        <Trend schema="VIMS" id="402" />
        <Trend schema="VIMS" id="403" />
        <Trend schema="VIMS" id="404" />
    </TrendConfiguration>
    <TrendConfiguration model="777G" >
        <Trend schema="VIMS" id="13" />
        <Trend schema="VIMS" id="20" />
        <Trend schema="VIMS" id="27" />
        <Trend schema="VIMS" id="32" />
        <Trend schema="VIMS" id="38" />
        <Trend schema="VIMS" id="51" />
        <Trend schema="VIMS" id="53" />
        <Trend schema="VIMS" id="70" />
        <Trend schema="VIMS" id="77" />
        <Trend schema="VIMS" id="79" />
        <Trend schema="VIMS" id="103" />
        <Trend schema="VIMS" id="105" />
        <Trend schema="VIMS" id="113" />
        <Trend schema="VIMS" id="192" />
        <Trend schema="VIMS" id="193" />
        <Trend schema="VIMS" id="194" />
        <Trend schema="VIMS" id="195" />
        <Trend schema="VIMS" id="196" />
        <Trend schema="VIMS" id="197" />
        <Trend schema="VIMS" id="198" />
        <Trend schema="VIMS" id="199" />
        <Trend schema="VIMS" id="220" />
        <Trend schema="VIMS" id="221" />
        <Trend schema="VIMS" id="299" />
        <Trend schema="VIMS" id="300" />
        <Trend schema="VIMS" id="301" />
        <Trend schema="VIMS" id="375" />
        <Trend schema="VIMS" id="376" />
        <Trend schema="VIMS" id="377" />
        <Trend schema="VIMS" id="378" />
        <Trend schema="VIMS" id="379" />
        <Trend schema="VIMS" id="380" />
        <Trend schema="VIMS" id="381" />
        <Trend schema="VIMS" id="382" />
        <Trend schema="VIMS" id="384" />
        <Trend schema="VIMS" id="385" />
        <Trend schema="VIMS" id="386" />
        <Trend schema="VIMS" id="387" />
        <Trend schema="VIMS" id="388" />
        <Trend schema="VIMS" id="389" />
        <Trend schema="VIMS" id="401" />
        <Trend schema="VIMS" id="402" />
        <Trend schema="VIMS" id="403" />
        <Trend schema="VIMS" id="404" />
        <Trend schema="VIMS" id="515" />
        <Trend schema="VIMS" id="516" />
        <Trend schema="VIMS" id="517" />
        <Trend schema="VIMS" id="518" />
        <Trend schema="VIMS" id="519" />
        <Trend schema="VIMS" id="532" />
        <Trend schema="VIMS" id="533" />
    </TrendConfiguration>
    <TrendConfiguration model="777G_LRC" >
        <Trend schema="VIMS" id="13" />
        <Trend schema="VIMS" id="20" />
        <Trend schema="VIMS" id="27" />
        <Trend schema="VIMS" id="32" />
        <Trend schema="VIMS" id="38" />
        <Trend schema="VIMS" id="51" />
        <Trend schema="VIMS" id="53" />
        <Trend schema="VIMS" id="70" />
        <Trend schema="VIMS" id="77" />
        <Trend schema="VIMS" id="79" />
        <Trend schema="VIMS" id="103" />
        <Trend schema="VIMS" id="105" />
        <Trend schema="VIMS" id="113" />
        <Trend schema="VIMS" id="192" />
        <Trend schema="VIMS" id="193" />
        <Trend schema="VIMS" id="194" />
        <Trend schema="VIMS" id="195" />
        <Trend schema="VIMS" id="196" />
        <Trend schema="VIMS" id="197" />
        <Trend schema="VIMS" id="198" />
        <Trend schema="VIMS" id="199" />
        <Trend schema="VIMS" id="220" />
        <Trend schema="VIMS" id="221" />
        <Trend schema="VIMS" id="299" />
        <Trend schema="VIMS" id="300" />
        <Trend schema="VIMS" id="301" />
        <Trend schema="VIMS" id="375" />
        <Trend schema="VIMS" id="376" />
        <Trend schema="VIMS" id="377" />
        <Trend schema="VIMS" id="378" />
        <Trend schema="VIMS" id="379" />
        <Trend schema="VIMS" id="380" />
        <Trend schema="VIMS" id="381" />
        <Trend schema="VIMS" id="382" />
        <Trend schema="VIMS" id="384" />
        <Trend schema="VIMS" id="385" />
        <Trend schema="VIMS" id="386" />
        <Trend schema="VIMS" id="387" />
        <Trend schema="VIMS" id="388" />
        <Trend schema="VIMS" id="389" />
        <Trend schema="VIMS" id="401" />
        <Trend schema="VIMS" id="402" />
        <Trend schema="VIMS" id="403" />
        <Trend schema="VIMS" id="404" />
        <Trend schema="VIMS" id="532" />
        <Trend schema="VIMS" id="533" />
    </TrendConfiguration>
    <TrendConfiguration model="784B" >
        <Trend schema="VIMS" id="2" />
        <Trend schema="VIMS" id="7" />
        <Trend schema="VIMS" id="12" />
        <Trend schema="VIMS" id="19" />
        <Trend schema="VIMS" id="26" />
        <Trend schema="VIMS" id="38" />
        <Trend schema="VIMS" id="42" />
        <Trend schema="VIMS" id="43" />
        <Trend schema="VIMS" id="57" />
        <Trend schema="VIMS" id="71" />
        <Trend schema="VIMS" id="72" />
        <Trend schema="VIMS" id="73" />
        <Trend schema="VIMS" id="74" />
        <Trend schema="VIMS" id="75" />
        <Trend schema="VIMS" id="76" />
        <Trend schema="VIMS" id="78" />
        <Trend schema="VIMS" id="82" />
        <Trend schema="VIMS" id="84" />
        <Trend schema="VIMS" id="113" />
        <Trend schema="VIMS" id="116" />
        <Trend schema="VIMS" id="117" />
    </TrendConfiguration>
    <TrendConfiguration model="785B" >
        <Trend schema="VIMS" id="2" />
        <Trend schema="VIMS" id="3" />
        <Trend schema="VIMS" id="7" />
        <Trend schema="VIMS" id="8" />
        <Trend schema="VIMS" id="12" />
        <Trend schema="VIMS" id="13" />
        <Trend schema="VIMS" id="19" />
        <Trend schema="VIMS" id="20" />
        <Trend schema="VIMS" id="26" />
        <Trend schema="VIMS" id="27" />
        <Trend schema="VIMS" id="31" />
        <Trend schema="VIMS" id="32" />
        <Trend schema="VIMS" id="38" />
        <Trend schema="VIMS" id="42" />
        <Trend schema="VIMS" id="43" />
        <Trend schema="VIMS" id="51" />
        <Trend schema="VIMS" id="53" />
        <Trend schema="VIMS" id="57" />
        <Trend schema="VIMS" id="66" />
        <Trend schema="VIMS" id="67" />
        <Trend schema="VIMS" id="68" />
        <Trend schema="VIMS" id="69" />
        <Trend schema="VIMS" id="70" />
        <Trend schema="VIMS" id="71" />
        <Trend schema="VIMS" id="72" />
        <Trend schema="VIMS" id="73" />
        <Trend schema="VIMS" id="74" />
        <Trend schema="VIMS" id="75" />
        <Trend schema="VIMS" id="76" />
        <Trend schema="VIMS" id="77" />
        <Trend schema="VIMS" id="78" />
        <Trend schema="VIMS" id="79" />
        <Trend schema="VIMS" id="82" />
        <Trend schema="VIMS" id="83" />
        <Trend schema="VIMS" id="84" />
        <Trend schema="VIMS" id="85" />
        <Trend schema="VIMS" id="103" />
        <Trend schema="VIMS" id="104" />
        <Trend schema="VIMS" id="105" />
        <Trend schema="VIMS" id="106" />
        <Trend schema="VIMS" id="113" />
        <Trend schema="VIMS" id="114" />
    </TrendConfiguration>
    <TrendConfiguration model="785B0700" >
        <Trend schema="VIMS" id="7" />
        <Trend schema="VIMS" id="12" />
        <Trend schema="VIMS" id="26" />
        <Trend schema="VIMS" id="31" />
        <Trend schema="VIMS" id="38" />
        <Trend schema="VIMS" id="43" />
        <Trend schema="VIMS" id="71" />
        <Trend schema="VIMS" id="72" />
        <Trend schema="VIMS" id="73" />
        <Trend schema="VIMS" id="74" />
        <Trend schema="VIMS" id="75" />
        <Trend schema="VIMS" id="76" />
        <Trend schema="VIMS" id="78" />
        <Trend schema="VIMS" id="103" />
        <Trend schema="VIMS" id="105" />
        <Trend schema="VIMS" id="113" />
        <Trend schema="VIMS" id="178" />
        <Trend schema="VIMS" id="179" />
        <Trend schema="VIMS" id="182" />
        <Trend schema="VIMS" id="185" />
        <Trend schema="VIMS" id="192" />
        <Trend schema="VIMS" id="193" />
        <Trend schema="VIMS" id="194" />
        <Trend schema="VIMS" id="195" />
        <Trend schema="VIMS" id="196" />
        <Trend schema="VIMS" id="197" />
        <Trend schema="VIMS" id="198" />
        <Trend schema="VIMS" id="199" />
        <Trend schema="VIMS" id="200" />
        <Trend schema="VIMS" id="222" />
        <Trend schema="VIMS" id="301" />
        <Trend schema="VIMS" id="302" />
        <Trend schema="VIMS" id="303" />
    </TrendConfiguration>
    <TrendConfiguration model="785C" >
        <Trend schema="VIMS" id="7" />
        <Trend schema="VIMS" id="12" />
        <Trend schema="VIMS" id="26" />
        <Trend schema="VIMS" id="37" />
        <Trend schema="VIMS" id="38" />
        <Trend schema="VIMS" id="71" />
        <Trend schema="VIMS" id="72" />
        <Trend schema="VIMS" id="73" />
        <Trend schema="VIMS" id="74" />
        <Trend schema="VIMS" id="75" />
        <Trend schema="VIMS" id="76" />
        <Trend schema="VIMS" id="78" />
        <Trend schema="VIMS" id="103" />
        <Trend schema="VIMS" id="105" />
        <Trend schema="VIMS" id="113" />
        <Trend schema="VIMS" id="178" />
        <Trend schema="VIMS" id="179" />
        <Trend schema="VIMS" id="182" />
        <Trend schema="VIMS" id="185" />
        <Trend schema="VIMS" id="192" />
        <Trend schema="VIMS" id="193" />
        <Trend schema="VIMS" id="194" />
        <Trend schema="VIMS" id="195" />
        <Trend schema="VIMS" id="196" />
        <Trend schema="VIMS" id="197" />
        <Trend schema="VIMS" id="198" />
        <Trend schema="VIMS" id="199" />
        <Trend schema="VIMS" id="200" />
        <Trend schema="VIMS" id="220" />
        <Trend schema="VIMS" id="221" />
        <Trend schema="VIMS" id="299" />
        <Trend schema="VIMS" id="300" />